# Basic dependabot.yml file with
# minimum configuration for two package managers (npm & docker)
# 

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # set the maximum number of pull requests to 10 (defaulst is 5)
    open-pull-requests-limit: 0
    # raise npm pull requests with the reviewers below
    reviewers:
      - "nickific"
    # set labels to pull requests triggered by dependabot
    labels:
      - "security"
